package TaskManager.backend_java.Services;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import TaskManager.backend_java.Dtos.TaskListDto;
import TaskManager.backend_java.Dtos.TasksDto;
import TaskManager.backend_java.Repositories.ProjectsRepository;
import TaskManager.backend_java.Repositories.Tasks;
import TaskManager.backend_java.Repositories.TasksRepository;
import TaskManager.backend_java.Repositories.UsersRepository;
import jakarta.transaction.Transactional;

@Service
public class TasksService {

	private String[] STATE_VARIABLES = { "TODO", "IN_PROGRESS", "DONE" };
	private String[] PRIORITY_VARIABLES = { "Low", "Hight" };

	@Autowired
	private TasksRepository tasksRepository;
	@Autowired
	private UsersRepository userRepository;
	@Autowired
	private ProjectsRepository projectRepository;

	public ResponseEntity<Object> createTask(TasksDto taskDto) {
		if (taskDto == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		List<String> nullfieldList = new ArrayList<>();
		if (taskDto.getProjectId() == null)
			nullfieldList.add("Project");
		if (taskDto.getTitle() == null)
			nullfieldList.add("Title");
		if (taskDto.getDescription() == null)
			nullfieldList.add("Description");
		if (taskDto.getPriority() == null)
			nullfieldList.add("Priority");
		if (!nullfieldList.isEmpty()) {
			ResponseEntity.status(HttpStatus.CONFLICT).body("Empty fields: " + String.join(", ", nullfieldList));
		}
		String taskId = autogeneratedTaskId(taskDto);
		if (taskId == null)
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Project is not exits");
		if (!Arrays.asList(STATE_VARIABLES).contains(taskDto.getState())) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("State value is not exists");
		}
		if (!Arrays.asList(PRIORITY_VARIABLES).contains(taskDto.getPriority())) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Priority value is not exists");
		}
		Tasks task = new Tasks(taskId, taskDto.getTitle(), taskDto.getDescription(), taskDto.getState(),
				taskDto.getPriority(), taskDto.getLimitDate(), LocalDate.now());
		if (taskDto.getUserId() != null) {
			Long userPk = userRepository.findPkByUserId(taskDto.getUserId());
			if (userPk == null)
				return ResponseEntity.status(HttpStatus.CONFLICT).body("User is not exits");
			task.setUserFk(userPk);
		}
		if (taskDto.getProjectId() != null) {
			Long projectPk = projectRepository.findPkByProjectId(taskDto.getProjectId());
			if (projectPk == null)
				return ResponseEntity.status(HttpStatus.CONFLICT).body("Project is not exits");
			task.setProjectFk(projectPk);
		}
		tasksRepository.save(task);
		if (tasksRepository.existByTaskId(taskDto.getTaskId())) {
			return ResponseEntity.status(HttpStatus.OK).body("Created task successfully");
		} else {
			return ResponseEntity.status(HttpStatus.OK).body("Created task unsuccessfully");
		}

	}

	private String autogeneratedTaskId(TasksDto taskDto) {
		Long projectPk = projectRepository.findPkByProjectId(taskDto.getProjectId());
		if (projectPk == null)
			return null;
		long n = tasksRepository.countByProjectFk(projectPk);
		String taskId = taskDto.getProjectId() + "-" + String.format("%04d", n + 1);
		return taskId;
	}

	public ResponseEntity<Object> findTaskDetails(TasksDto taskDto) {
		if (taskDto == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		Tasks task = tasksRepository.findByTaskId(taskDto.getTaskId());
		if (task == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is not exits");
		}
		String userId = null;
		String projectId = null;
		if (task.getUserFk() != null) {
			userId = userRepository.findUserIdByPk(task.getUserFk());
		}
		if (task.getProjectFk() != null) {
			projectId = projectRepository.findProjectIdByPk(task.getProjectFk());
		}
		TasksDto responseTaskDto = new TasksDto(task.getPk(), task.getTaskId(), task.getTitle(), task.getDescription(),
				task.getState(), task.getPriority(), task.getLimitDate(), task.getCreatedOn(), task.getProjectFk(),
				task.getUserFk(), projectId, userId);
		return ResponseEntity.status(HttpStatus.OK).body(responseTaskDto);
	}

	public ResponseEntity<Object> findTasksList(TasksDto taskDto) {
		if (taskDto == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		List<Tasks> listTask = tasksRepository.findByFilters(taskDto.getState(), taskDto.getProjectFk(),
				taskDto.getUserFk());
		List<TaskListDto> listTaskDto = new ArrayList<>();
		for (Tasks task : listTask) {
			TaskListDto taskListDto = new TaskListDto();
			String userId = userRepository.findUserIdByPk(task.getUserFk());
			if (userId != null)
				taskListDto.setAsigned(userId);
			String projectId = projectRepository.findProjectIdByPk(task.getPk());
			if (projectId != null)
				taskListDto.setProjectId(projectId);
			taskListDto.setCreatedOn(task.getCreatedOn());
			taskListDto.setPriority(task.getPriority());
			taskListDto.setState(task.getState());
			taskListDto.setTaskId(task.getTaskId());
			listTaskDto.add(taskListDto);
		}
		return ResponseEntity.status(HttpStatus.OK).body(listTaskDto);
	}

	public ResponseEntity<Object> updateTask(TasksDto taskDto) {
		if (taskDto == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		Tasks task = tasksRepository.findByTaskId(taskDto.getTaskId());
		if (task == null) {
			return ResponseEntity.status(HttpStatus.OK).body("Task not exist");
		}
		if (!Arrays.asList(STATE_VARIABLES).contains(taskDto.getState()) && taskDto.getState() != null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("State value is not exists");
		}
		if (!Arrays.asList(PRIORITY_VARIABLES).contains(taskDto.getPriority()) && taskDto.getPriority() != null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Priority value is not exists");
		}
		if (taskDto.getTitle() != task.getTitle())
			task.setTitle(taskDto.getTitle());
		if (taskDto.getDescription() != task.getDescription())
			task.setDescription(taskDto.getDescription());
		if (taskDto.getLimitDate() != task.getLimitDate())
			task.setLimitDate(taskDto.getLimitDate());
		if (taskDto.getPriority() != task.getPriority())
			task.setPriority(taskDto.getPriority());
		if (taskDto.getState() != task.getState())
			task.setState(taskDto.getState());
		String userId = userRepository.findUserIdByPk(task.getUserFk());
		if (taskDto.getUserId() != userId) {
			Long userPk = userRepository.findPkByUserId(taskDto.getUserId());
			task.setUserFk(userPk);
		}
		tasksRepository.save(task);
		return ResponseEntity.status(HttpStatus.OK).body("Update task successfully");
	}

	public ResponseEntity<Object> modifyState(String taskId, String state) {
		if (taskId == null || state == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		Tasks task = tasksRepository.findByTaskId(taskId);
		if (task == null) {
			return ResponseEntity.status(HttpStatus.OK).body("Task not exist");
		}
		if (!Arrays.asList(STATE_VARIABLES).contains(state)) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("State value is not exists");
		}
		task.setState(state);
		tasksRepository.save(task);
		return ResponseEntity.status(HttpStatus.OK).body("Update state successfully");
	}

	@Transactional
	public ResponseEntity<Object> deleteTask(String taskId) {
		if (taskId == null) {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Task is null");
		}
		Tasks task = tasksRepository.findByTaskId(taskId);
		tasksRepository.delete(task);
		if (tasksRepository.existByTaskId(taskId)) {
			return ResponseEntity.status(HttpStatus.OK).body("Deleted task successfully");
		} else {
			return ResponseEntity.status(HttpStatus.OK).body("Deleted task unsuccessfully");
		}
	}

}
