using backend_dotnet.Data.Dtos;

namespace backend_dotnet.Services
{

    public class TasksServices
    {

        public readonly TaskManagerContext _dbContext;

        private static readonly string[] STATE_VARIABLES = { "TODO", "IN_PROGRESS", "DONE" };
        private static readonly string[] PRIORITY_VARIABLES = { "Low", "High" };

        public TasksServices(TaskManagerContext dbContext)
        {
            _dbContext = dbContext;
        }

        public List<TaskListDto> GetTasksList(TaskListDto filter)
        {
            var query = _dbContext.Tasks.AsQueryable();
            if (!string.IsNullOrEmpty(filter.State))
                query = query.Where(t => t.State == filter.State);

            if (!string.IsNullOrEmpty(filter.ProjectId))
            {
                long? projectPk = _dbContext.Projects
                    .Where(p => p.ProjectId == filter.ProjectId)
                    .Select(p => (long?)p.Pk)
                    .FirstOrDefault();
                if (projectPk.HasValue)
                    query = query.Where(t => t.ProjectFk == projectPk.Value);
            }

            if (!string.IsNullOrEmpty(filter.UserId))
            {
                long? userPk = _dbContext.Users
                    .Where(u => u.UserId == filter.UserId)
                    .Select(u => (long?)u.Pk)
                    .FirstOrDefault();
                if (userPk.HasValue)
                    query = query.Where(t => t.UserFk == userPk.Value);
            }

            var tasks = query.ToList();
            var result = new List<TaskListDto>();
            foreach (var task in tasks)
            {
                string? userId = _dbContext.Users
                    .Where(u => u.Pk == task.UserFk)
                    .Select(u => u.UserId)
                    .FirstOrDefault();
                string? projectId = _dbContext.Projects
                    .Where(p => p.Pk == task.ProjectFk)
                    .Select(p => p.ProjectId)
                    .FirstOrDefault();
                result.Add(new TaskListDto(task.TaskId, task.Title, task.Description, task.State,
                    task.Priority, task.CreatedOn, task.LimitDate, projectId, task.ProjectFk, userId, task.UserFk));
            }
            return result;
        }

        public TaskListDto? GetTask(string taskId)
        {
            if (string.IsNullOrEmpty(taskId)) return null;
            var task = _dbContext.Tasks.FirstOrDefault(t => t.TaskId == taskId);
            if (task == null) return null;
            string? userId = _dbContext.Users
                .Where(u => u.Pk == task.UserFk)
                .Select(u => u.UserId)
                .FirstOrDefault();
            string? projectId = _dbContext.Projects
                .Where(p => p.Pk == task.ProjectFk)
                .Select(p => p.ProjectId)
                .FirstOrDefault();
            return new TaskListDto(task.TaskId, task.Title, task.Description, task.State,
                task.Priority, task.CreatedOn, task.LimitDate, projectId, task.ProjectFk, userId, task.UserFk);
        }

        public bool CreateTask(TasksDto dto)
        {
            if (dto == null || dto.Title == null || dto.Description == null
                || dto.Priority == null || dto.State == null || !dto.ProjectFk.HasValue)
                return false;
            if (!STATE_VARIABLES.Contains(dto.State))
                throw new ArgumentException("State value is not valid: " + dto.State);
            if (!PRIORITY_VARIABLES.Contains(dto.Priority))
                throw new ArgumentException("Priority value is not valid: " + dto.Priority);

            var project = _dbContext.Projects.FirstOrDefault(p => p.Pk == dto.ProjectFk.Value);
            if (project == null) return false;

            if (dto.UserFk.HasValue)
            {
                bool userExists = _dbContext.Users.Any(u => u.Pk == dto.UserFk.Value);
                if (!userExists) return false;
            }

            string taskId = AutogeneratedTaskId(project.ProjectId, project.Pk);
            Tasks task = new Tasks
            {
                TaskId = taskId,
                Title = dto.Title,
                Description = dto.Description,
                State = dto.State,
                Priority = dto.Priority,
                CreatedOn = DateOnly.FromDateTime(DateTime.Now),
                LimitDate = dto.LimitDate,
                ProjectFk = dto.ProjectFk.Value,
                UserFk = dto.UserFk
            };
            _dbContext.Tasks.Add(task);
            _dbContext.SaveChanges();
            return _dbContext.Tasks.Any(t => t.TaskId == taskId);
        }

        private string AutogeneratedTaskId(string projectId, long projectPk)
        {
            long count = _dbContext.Tasks.Count(t => t.ProjectFk == projectPk);
            return projectId + "-" + (count + 1).ToString("D4");
        }

        public bool DeleteTask(string taskId)
        {
            if (string.IsNullOrEmpty(taskId)) return false;
            var task = _dbContext.Tasks.FirstOrDefault(t => t.TaskId == taskId);
            if (task == null) return false;
            _dbContext.Tasks.Remove(task);
            _dbContext.SaveChanges();
            return true;
        }

        public bool UpdateTask(string taskId, TasksDto dto)
        {
            if (string.IsNullOrEmpty(taskId) || dto == null) return false;
            var task = _dbContext.Tasks.FirstOrDefault(t => t.TaskId == taskId);
            if (task == null) return false;
            if (dto.State != null && !STATE_VARIABLES.Contains(dto.State))
                throw new ArgumentException("State value is not valid: " + dto.State);
            if (dto.Priority != null && !PRIORITY_VARIABLES.Contains(dto.Priority))
                throw new ArgumentException("Priority value is not valid: " + dto.Priority);

            task.Title = dto.Title ?? task.Title;
            task.Description = dto.Description ?? task.Description;
            task.Priority = dto.Priority ?? task.Priority;
            task.State = dto.State ?? task.State;
            task.LimitDate = dto.LimitDate ?? task.LimitDate;
            if (dto.UserFk.HasValue)
            {
                bool userExists = _dbContext.Users.Any(u => u.Pk == dto.UserFk.Value);
                if (userExists) task.UserFk = dto.UserFk.Value;
            }
            _dbContext.SaveChanges();
            return true;
        }

        public bool UpdateState(string taskId, string state)
        {
            if (string.IsNullOrEmpty(taskId) || string.IsNullOrEmpty(state)) return false;
            if (!STATE_VARIABLES.Contains(state))
                throw new ArgumentException("State value is not valid: " + state);
            var task = _dbContext.Tasks.FirstOrDefault(t => t.TaskId == taskId);
            if (task == null) return false;
            task.State = state;
            _dbContext.SaveChanges();
            return true;
        }
    }
}
